version: '3'
services:
  frontend:
    build: ./frontend
    container_name: ${CONTAINER_NAME_FRONTEND}
    volumes:
      - ./frontend/www:/var/www/html
    env_file: .env
    ports:
      - '80:80'
    depends_on:
      - web

  web:
    build: ./web
    container_name: ${CONTAINER_NAME_WEB}
    command: npm run dev
    volumes:
      - ./web:/usr/app
      - /usr/app/node_modules
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
    env_file: .env

  mongodb:
    build:
      context: ./db
    container_name: ${CONTAINER_NAME_MONGO}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB_NAME}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_DB_PORT}:27017"
networks:
  default:
    external: true
    name: boulez_network